# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo
  font: native
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo landing page theme powered by Hugo Blox website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    #show_logo: true
    show_day_night: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.png"
      # width: fit-content
      # height: 120px
    button:
      enable: false
      text: "Get Started"
      url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true
    highlight_active_link: true
  # image:
  #   width: 400px
  #   height: 400px

body:
  text-align: justify

# Site footer
footer:
  copyright:
    notice: 'Â© 2023 NPL. This work is licensed under GNU LGPL-3.0'


# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# # Site features

# features:
#   syntax_highlighter:
#     enable: false
#     extra_languages:
#       - r
#       - latex
#   math:
#     enable: false
#   privacy_pack:
#     enable: false
#   #repository:
#   #  url: 'https://github.com/<username>/<repository>'
#   #  content_dir: content
#   #  branch: main
#   avatar:
#     gravatar: false
#     shape: circle
#   comment:
#     provider: ''
#     disqus:
#       shortname: ''
#       show_count: true
#     commento:
#       url: ''
#   search:
#     provider: wowchemy
#     algolia:
#       app_id: ''
#       api_key: ''
#       index_name: ''
#       show_logo: false
#   map:
#     provider: 'mapnik'
#     api_key: ''
#     zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true